apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_HOST: {{ .Values.secrets.DB_HOST | b64enc }}
  DB_NAME: {{ .Values.secrets.DB_NAME | b64enc }}
  DB_USER: {{ .Values.secrets.DB_USER | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc }}
